apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: maintenance-nginx
  name: maintenance-nginx
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}
