apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web2-deployment
  name: web2-deployment
  namespace: static-websites
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-2
    spec:
      containers:
      - image: vietpl/web2:0.5
        name: web-2
        resources: {}
        ports:
            - containerPort: 80
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: web2-service
  name: web2-service
  namespace: static-websites
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: web-2
status:
  loadBalancer: {}