apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: whoami-pod
  name: whoami-pod
spec:
  containers:
  - image: containous/whoami
    name: whoami-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
